using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Text;

namespace Broiler.JavaScript.BuiltIns.Temporal.Tz;

// The bundled IANA time-zone database (generated by scripts/tzdata/generate_tzdata.py and embedded as
// Temporal/Tz/tzdata.bin). It makes Temporal / Date named-zone resolution, offset computation and
// transition lookup independent of the host operating system's tz database. The data is the IANA
// release noted in Version; zones carry their own TZif transition table while links (backward
// aliases) resolve to their target's data but keep their own identifier.
internal static class IanaTimeZoneDatabase
{
    private const string ResourceName = "Broiler.JavaScript.BuiltIns.Temporal.Tz.tzdata.bin";

    private static readonly object Gate = new();
    private static Dictionary<string, byte[]> _zoneData;       // canonical zone id -> TZif bytes
    private static Dictionary<string, string> _links;          // alias id -> target zone id
    private static Dictionary<string, string> _foldedNames;    // UPPER(id) -> proper-cased id (zones + links)
    private static Dictionary<string, IanaTimeZone> _parsed;   // resolved id -> parsed zone (cache)
    private static string _version;

    public static string Version { get { EnsureLoaded(); return _version; } }

    // All zone and link identifiers, in their canonical casing.
    public static IEnumerable<string> AllNames
    {
        get { EnsureLoaded(); foreach (var n in _foldedNames.Values) yield return n; }
    }

    // Case-insensitively resolves an identifier to its canonical-cased name (a zone or a link keeps
    // its own name — links are NOT replaced by their primary zone). Returns false for an unknown id.
    public static bool TryCanonicalize(string id, out string canonical)
    {
        EnsureLoaded();
        if (id != null && _foldedNames.TryGetValue(id.ToUpperInvariant(), out canonical))
            return true;
        canonical = null;
        return false;
    }

    // The primary (target) zone identifier an id resolves to: a link returns its target, a zone
    // returns itself, an unknown id (a numeric offset / UTC) is returned unchanged. Used to compare
    // whether two identifiers denote the same zone. The lookup is case-insensitive.
    public static string GetPrimary(string id)
    {
        EnsureLoaded();
        if (id == null || !_foldedNames.TryGetValue(id.ToUpperInvariant(), out var properCase))
            return id;
        return _links.TryGetValue(properCase, out var target) ? target : properCase;
    }

    // The parsed zone for an identifier (a link resolves to its target's transition data while
    // keeping the requested id), or null when the id is not a known zone/link. The lookup is
    // case-insensitive.
    public static IanaTimeZone Get(string id)
    {
        EnsureLoaded();
        if (id == null || !_foldedNames.TryGetValue(id.ToUpperInvariant(), out var properCase))
            return null;

        lock (Gate)
        {
            if (_parsed.TryGetValue(properCase, out var cached))
                return cached;

            var dataKey = _links.TryGetValue(properCase, out var target) ? target : properCase;
            if (!_zoneData.TryGetValue(dataKey, out var tzif))
                return null;

            var zone = TzifReader.Parse(properCase, tzif);
            _parsed[properCase] = zone;
            return zone;
        }
    }

    // CLDR/ECMAScript non-primary identifiers that tzdata ships as standalone Zones.
    // Each resolves to the primary IANA zone it is an alias of.
    private static readonly (string Alias, string Target)[] LegacyPrimaryAliases =
    {
        ("CET", "Europe/Brussels"),
        ("CST6CDT", "America/Chicago"),
        ("EET", "Europe/Athens"),
        ("EST", "America/Panama"),
        ("EST5EDT", "America/New_York"),
        ("HST", "Pacific/Honolulu"),
        ("MET", "Europe/Brussels"),
        ("MST", "America/Phoenix"),
        ("MST7MDT", "America/Denver"),
        ("PST8PDT", "America/Los_Angeles"),
        ("WET", "Europe/Lisbon"),
    };

    private static void EnsureLoaded()
    {
        if (_zoneData != null) return;
        lock (Gate)
        {
            if (_zoneData != null) return;

            using var resource = typeof(IanaTimeZoneDatabase).Assembly.GetManifestResourceStream(ResourceName)
                ?? throw new InvalidOperationException($"Missing embedded resource {ResourceName}");
            using var inflate = new DeflateStream(resource, CompressionMode.Decompress);
            using var ms = new MemoryStream();
            inflate.CopyTo(ms);
            var bytes = ms.ToArray();

            var (zones, links, version) = Parse(bytes);

            // The legacy "pseudo" zones (CET, EET, …) and POSIX-style zones (CST6CDT, …)
            // are shipped as standalone Zones in tzdata, but ECMAScript / CLDR classify
            // them as NON-primary time-zone identifiers that resolve to a primary IANA
            // zone. Register those resolutions as links (kept only when the embedded data
            // hasn't already provided one and the target zone exists) so TimeZoneEquals
            // and offset resolution treat e.g. `CET` as `Europe/Brussels`
            // (test262 intl402/Temporal/ZonedDateTime/links).
            foreach (var (alias, target) in LegacyPrimaryAliases)
            {
                if (!links.ContainsKey(alias) && zones.ContainsKey(target))
                    links[alias] = target;
            }

            var folded = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var name in zones.Keys) folded[name.ToUpperInvariant()] = name;
            foreach (var alias in links.Keys) folded[alias.ToUpperInvariant()] = alias;

            _zoneData = zones;
            _links = links;
            _foldedNames = folded;
            _parsed = new Dictionary<string, IanaTimeZone>(StringComparer.Ordinal);
            _version = version;
        }
    }

    private static (Dictionary<string, byte[]> zones, Dictionary<string, string> links, string version) Parse(byte[] data)
    {
        var pos = 0;
        if (data.Length < 8 || data[0] != 'T' || data[1] != 'Z' || data[2] != 'D' || data[3] != 'B')
            throw new InvalidDataException("Invalid tzdata.bin header");
        pos = 4;
        _ = ReadInt32(data, ref pos); // format version
        var version = ReadString(data, ref pos);

        var zoneCount = ReadInt32(data, ref pos);
        var zones = new Dictionary<string, byte[]>(zoneCount, StringComparer.Ordinal);
        for (var i = 0; i < zoneCount; i++)
        {
            var name = ReadString(data, ref pos);
            var len = ReadInt32(data, ref pos);
            var tzif = new byte[len];
            System.Array.Copy(data, pos, tzif, 0, len);
            pos += len;
            zones[name] = tzif;
        }

        var linkCount = ReadInt32(data, ref pos);
        var links = new Dictionary<string, string>(linkCount, StringComparer.Ordinal);
        for (var i = 0; i < linkCount; i++)
        {
            var alias = ReadString(data, ref pos);
            var target = ReadString(data, ref pos);
            links[alias] = target;
        }

        return (zones, links, version);
    }

    private static int ReadInt32(byte[] d, ref int pos)
    {
        var v = d[pos] | (d[pos + 1] << 8) | (d[pos + 2] << 16) | (d[pos + 3] << 24);
        pos += 4;
        return v;
    }

    private static string ReadString(byte[] d, ref int pos)
    {
        var len = ReadInt32(d, ref pos);
        var s = Encoding.UTF8.GetString(d, pos, len);
        pos += len;
        return s;
    }
}
