using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Broiler.JavaScript.Ast;
using Broiler.JavaScript.Ast.Expressions;
using Broiler.JavaScript.Ast.Misc;
using Broiler.JavaScript.Ast.Statements;
using Broiler.JavaScript.Parser;

namespace Broiler.JavaScript.Portable;

/// <summary>Offline compiler for the documented numeric statement subset.</summary>
public sealed class PortableCompiler
{
    private readonly List<PortableInstruction> instructions = [];
    private readonly Dictionary<string, int> parameters = new(StringComparer.Ordinal);
    private readonly Dictionary<string, int> locals = new(StringComparer.Ordinal);
    private int stackDepth;
    private int maximumStack;

    public PortableProgram Compile(string source)
    {
        if (string.IsNullOrWhiteSpace(source))
            throw new ArgumentException("Source is required.", nameof(source));

        instructions.Clear();
        parameters.Clear();
        locals.Clear();
        stackDepth = 0;
        maximumStack = 0;

        AstProgram program;
        var pool = new FastPool();
        try
        {
            var parser = new FastParser(new FastTokenStream(pool, source));
            program = parser.ParseProgram();
        }
        finally
        {
            pool.Dispose();
        }
        var topLevel = ToList(program.Statements);
        if (topLevel.Count != 1
            || topLevel[0] is not AstExpressionStatement { Expression: AstFunctionExpression function })
        {
            throw Unsupported("exactly one top-level function declaration");
        }
        if (function.Async || function.Generator || function.IsArrowFunction || function.Body is not AstBlock body)
            throw Unsupported("an ordinary function with a block body");

        var parameterEnumerator = function.Params.GetFastEnumerator();
        while (parameterEnumerator.MoveNext(out var parameter))
        {
            if (parameter.Init != null || parameter.Identifier is not AstIdentifier identifier)
                throw Unsupported("simple identifier parameters");
            if (!parameters.TryAdd(identifier.Name.Value, parameters.Count))
                throw Unsupported("unique parameter names");
        }

        CompileBlock(body);
        if (instructions.Count == 0 || instructions[^1].OpCode != PortableOpCode.Return)
            throw Unsupported("an explicit return on every compiled path");

        return new PortableProgram(
            function.Id?.Name.Value ?? "anonymous",
            parameters.Count,
            locals.Count,
            Math.Max(1, maximumStack),
            [.. instructions]);
    }

    public static string EmitCSharp(
        PortableProgram program,
        string namespaceName,
        string typeName)
    {
        ArgumentNullException.ThrowIfNull(program);
        if (string.IsNullOrWhiteSpace(namespaceName) || string.IsNullOrWhiteSpace(typeName))
            throw new ArgumentException("A namespace and type name are required.");

        var output = new StringBuilder();
        output.AppendLine("// <auto-generated />");
        output.AppendLine("using Broiler.JavaScript.Portable;");
        output.AppendLine();
        output.Append("namespace ").Append(namespaceName).AppendLine(";");
        output.AppendLine();
        output.Append("internal static class ").Append(typeName).AppendLine();
        output.AppendLine("{");
        output.AppendLine("    internal static readonly PortableProgram Value = new(");
        output.Append("        \"").Append(program.Name.Replace("\"", "\\\"", StringComparison.Ordinal)).AppendLine("\",");
        output.Append("        ").Append(program.ParameterCount).AppendLine(",");
        output.Append("        ").Append(program.LocalCount).AppendLine(",");
        output.Append("        ").Append(program.MaximumStack).AppendLine(",");
        output.AppendLine("        new PortableInstruction[]");
        output.AppendLine("        {");
        foreach (var instruction in program.Instructions)
        {
            output.Append("            new(PortableOpCode.").Append(instruction.OpCode);
            if (instruction.Operand != 0 || instruction.Number != 0)
                output.Append(", ").Append(instruction.Operand);
            if (instruction.Number != 0)
                output.Append(", ").Append(instruction.Number.ToString("R", CultureInfo.InvariantCulture));
            output.AppendLine("),");
        }
        output.AppendLine("        });");
        output.AppendLine("}");
        return output.ToString();
    }

    private void CompileBlock(AstBlock block)
    {
        var enumerator = block.Statements.GetFastEnumerator();
        while (enumerator.MoveNext(out var statement))
            CompileStatement(statement);
    }

    private void CompileStatement(AstStatement statement)
    {
        switch (statement)
        {
            case AstBlock block:
                CompileBlock(block);
                return;
            case AstVariableDeclaration declaration:
                CompileVariableDeclaration(declaration);
                return;
            case AstExpressionStatement expressionStatement:
                CompileExpression(expressionStatement.Expression);
                Emit(PortableOpCode.Pop);
                return;
            case AstReturnStatement { Argument: { } argument }:
                CompileExpression(argument);
                Emit(PortableOpCode.Return);
                return;
            case AstWhileStatement whileStatement:
                CompileWhile(whileStatement);
                return;
            case AstForStatement forStatement:
                CompileFor(forStatement);
                return;
            case AstIfStatement ifStatement:
                CompileIf(ifStatement);
                return;
            default:
                throw Unsupported(statement.Type.ToString());
        }
    }

    private void CompileVariableDeclaration(AstVariableDeclaration declaration)
    {
        if (declaration.Using || declaration.AwaitUsing || declaration.Kind != FastVariableKind.Var)
            throw Unsupported("var numeric variables");
        var enumerator = declaration.Declarators.GetFastEnumerator();
        while (enumerator.MoveNext(out var declarator))
        {
            if (declarator.Identifier is not AstIdentifier identifier)
                throw Unsupported("identifier variable declarations");
            var index = GetOrAddLocal(identifier.Name.Value);
            if (declarator.Init == null)
                Emit(PortableOpCode.PushConstant, number: 0);
            else
                CompileExpression(declarator.Init);
            Emit(PortableOpCode.StoreLocal, index);
        }
    }

    private void CompileWhile(AstWhileStatement statement)
    {
        var start = instructions.Count;
        CompileExpression(statement.Test);
        var exit = EmitPlaceholder(PortableOpCode.JumpIfFalse);
        CompileStatement(statement.Body);
        Emit(PortableOpCode.Jump, start);
        Patch(exit, instructions.Count);
    }

    private void CompileFor(AstForStatement statement)
    {
        if (statement.Init is AstStatement initStatement)
            CompileStatement(initStatement);
        else if (statement.Init is AstExpression initExpression && initExpression.Type != FastNodeType.EmptyExpression)
        {
            CompileExpression(initExpression);
            Emit(PortableOpCode.Pop);
        }

        var start = instructions.Count;
        CompileExpression(statement.Test);
        var exit = EmitPlaceholder(PortableOpCode.JumpIfFalse);
        CompileStatement(statement.Body);
        if (statement.Update.Type != FastNodeType.EmptyExpression)
        {
            CompileExpression(statement.Update);
            Emit(PortableOpCode.Pop);
        }
        Emit(PortableOpCode.Jump, start);
        Patch(exit, instructions.Count);
    }

    private void CompileIf(AstIfStatement statement)
    {
        CompileExpression(statement.Test);
        var falseJump = EmitPlaceholder(PortableOpCode.JumpIfFalse);
        CompileStatement(statement.True);
        if (statement.False == null)
        {
            Patch(falseJump, instructions.Count);
            return;
        }

        var endJump = EmitPlaceholder(PortableOpCode.Jump);
        Patch(falseJump, instructions.Count);
        CompileStatement(statement.False);
        Patch(endJump, instructions.Count);
    }

    private void CompileExpression(AstExpression expression)
    {
        switch (expression)
        {
            case AstLiteral { TokenType: TokenTypes.Number } literal:
                Emit(PortableOpCode.PushConstant, number: literal.NumericValue);
                return;
            case AstIdentifier identifier:
                EmitLoad(identifier.Name.Value);
                return;
            case AstUnaryExpression unary when unary.Operator is UnaryOperator.Increment or UnaryOperator.Decrement:
                CompileUpdate(unary);
                return;
            case AstBinaryExpression binary when IsAssignment(binary.Operator):
                CompileAssignment(binary);
                return;
            case AstBinaryExpression binary:
                CompileExpression(binary.Left);
                CompileExpression(binary.Right);
                Emit(BinaryOpCode(binary.Operator));
                return;
            default:
                throw Unsupported(expression.Type.ToString());
        }
    }

    private void CompileAssignment(AstBinaryExpression assignment)
    {
        if (assignment.Left is not AstIdentifier identifier || !locals.TryGetValue(identifier.Name.Value, out var index))
            throw Unsupported("assignments to declared locals");

        if (assignment.Operator == TokenTypes.Assign)
        {
            CompileExpression(assignment.Right);
        }
        else
        {
            Emit(PortableOpCode.LoadLocal, index);
            CompileExpression(assignment.Right);
            Emit(assignment.Operator switch
            {
                TokenTypes.AssignAdd => PortableOpCode.Add,
                TokenTypes.AssignSubtract => PortableOpCode.Subtract,
                TokenTypes.AssignMultiply => PortableOpCode.Multiply,
                TokenTypes.AssignDivide => PortableOpCode.Divide,
                TokenTypes.AssignMod => PortableOpCode.Remainder,
                _ => throw Unsupported(assignment.Operator.ToString()),
            });
        }

        Emit(PortableOpCode.Duplicate);
        Emit(PortableOpCode.StoreLocal, index);
    }

    private void CompileUpdate(AstUnaryExpression update)
    {
        if (update.Argument is not AstIdentifier identifier || !locals.TryGetValue(identifier.Name.Value, out var index))
            throw Unsupported("updates of declared locals");

        Emit(PortableOpCode.LoadLocal, index);
        if (!update.Prefix)
            Emit(PortableOpCode.Duplicate);
        Emit(PortableOpCode.PushConstant, number: 1);
        Emit(update.Operator == UnaryOperator.Increment ? PortableOpCode.Add : PortableOpCode.Subtract);
        if (update.Prefix)
            Emit(PortableOpCode.Duplicate);
        Emit(PortableOpCode.StoreLocal, index);
    }

    private void EmitLoad(string name)
    {
        if (locals.TryGetValue(name, out var local))
            Emit(PortableOpCode.LoadLocal, local);
        else if (parameters.TryGetValue(name, out var parameter))
            Emit(PortableOpCode.LoadArgument, parameter);
        else
            throw Unsupported($"unresolved identifier '{name}'");
    }

    private int GetOrAddLocal(string name)
    {
        if (parameters.ContainsKey(name))
            throw Unsupported("locals that do not redeclare parameters");
        if (!locals.TryGetValue(name, out var index))
        {
            index = locals.Count;
            locals.Add(name, index);
        }
        return index;
    }

    private static bool IsAssignment(TokenTypes token)
        => token is TokenTypes.Assign or TokenTypes.AssignAdd or TokenTypes.AssignSubtract
            or TokenTypes.AssignMultiply or TokenTypes.AssignDivide or TokenTypes.AssignMod;

    private static PortableOpCode BinaryOpCode(TokenTypes token) => token switch
    {
        TokenTypes.Plus => PortableOpCode.Add,
        TokenTypes.Minus => PortableOpCode.Subtract,
        TokenTypes.Multiply => PortableOpCode.Multiply,
        TokenTypes.Divide => PortableOpCode.Divide,
        TokenTypes.Mod => PortableOpCode.Remainder,
        TokenTypes.Less => PortableOpCode.LessThan,
        TokenTypes.LessOrEqual => PortableOpCode.LessThanOrEqual,
        TokenTypes.Greater => PortableOpCode.GreaterThan,
        TokenTypes.GreaterOrEqual => PortableOpCode.GreaterThanOrEqual,
        TokenTypes.Equal or TokenTypes.StrictlyEqual => PortableOpCode.Equal,
        TokenTypes.NotEqual or TokenTypes.StrictlyNotEqual => PortableOpCode.NotEqual,
        _ => throw Unsupported(token.ToString()),
    };

    private int EmitPlaceholder(PortableOpCode opCode)
    {
        var index = instructions.Count;
        Emit(opCode);
        return index;
    }

    private void Patch(int index, int target)
        => instructions[index] = instructions[index] with { Operand = target };

    private void Emit(PortableOpCode opCode, int operand = 0, double number = 0)
    {
        instructions.Add(new PortableInstruction(opCode, operand, number));
        stackDepth += StackDelta(opCode);
        if (stackDepth < 0)
            throw new InvalidOperationException("Portable compiler produced an operand-stack underflow.");
        maximumStack = Math.Max(maximumStack, stackDepth);
    }

    private static int StackDelta(PortableOpCode opCode) => opCode switch
    {
        PortableOpCode.PushConstant or PortableOpCode.LoadArgument or PortableOpCode.LoadLocal
            or PortableOpCode.Duplicate => 1,
        PortableOpCode.StoreLocal or PortableOpCode.Pop or PortableOpCode.JumpIfFalse
            or PortableOpCode.Return => -1,
        PortableOpCode.Add or PortableOpCode.Subtract or PortableOpCode.Multiply
            or PortableOpCode.Divide or PortableOpCode.Remainder or PortableOpCode.LessThan
            or PortableOpCode.LessThanOrEqual or PortableOpCode.GreaterThan
            or PortableOpCode.GreaterThanOrEqual or PortableOpCode.Equal or PortableOpCode.NotEqual => -1,
        _ => 0,
    };

    private static List<AstStatement> ToList(
        Broiler.JavaScript.ExpressionCompiler.Core.IFastEnumerable<AstStatement> values)
    {
        var result = new List<AstStatement>(values.Count);
        var enumerator = values.GetFastEnumerator();
        while (enumerator.MoveNext(out var value))
            result.Add(value);
        return result;
    }

    private static NotSupportedException Unsupported(string feature)
        => new($"The portable compiler does not support {feature}.");
}
