using Broiler.JavaScript.Runtime;
using Broiler.JavaScript.Storage;

namespace Broiler.JavaScript.Engine.Core;

using Broiler.JavaScript.Engine;

/// <summary>
/// Creates the JavaScript <c>Object</c> constructor and wires its prototype
/// methods and static methods.  This was formerly source-generated by the
/// <c>JSClassGenerator</c> as <c>JSObject.CreateClass</c>.  Because
/// <c>JSObject</c> now lives in the Runtime assembly (which cannot reference
/// Core), the factory is provided here and exposed via
/// <see cref="JSEngine.CreateObjectClass"/>.
///
/// Uses <see cref="JSValue.CreateFunction(JSFunctionDelegate, string, string, int, bool)"/>
/// factory delegates instead of directly constructing <c>JSFunction</c>,
/// because <c>JSFunction</c> now lives in the BuiltIns assembly.
/// </summary>
internal static class ObjectClassFactory
{
    internal static JSValue CreateObjectClass(JSObject context, bool register)
    {
        KeyString objectKey = "Object";

        // ES2024 §20.1.1.1 Object ( [ value ] ), step 1: when NewTarget is present and is NOT the
        // Object constructor itself (i.e. a subclass — `new (class extends Object {})(...)` or
        // Reflect.construct(Object, …, Subclass)), create a fresh ordinary object from
        // NewTarget.prototype and IGNORE the value argument. The engine's [[Construct]] already
        // allocated that object (with NewTarget.prototype) as `this`, so returning it is the
        // OrdinaryCreateFromConstructor result. Otherwise (NewTarget is undefined or is Object
        // itself) fall through to the plain Object behaviour (ToObject / a new ordinary object).
        //
        // CurrentNewTarget is the new.target of the construct in progress; CallStackItem clears it on
        // entering a JS frame, so while Object's own native [[Construct]] runs it is set only for this
        // construct (and is null for a plain `Object(value)` call).
        JSObject objectClass = null;
        JSValue ObjectConstructor(in Arguments a)
        {
            var newTarget = (JSEngine.Current as IJSExecutionContext)?.CurrentNewTarget;
            if (newTarget != null && !ReferenceEquals(newTarget, objectClass) && a.This is JSObject self)
                return self;

            return JSObject.Constructor(a);
        }

        // §20.1.1 The Object constructor has length 1 (its single optional `value` parameter).
        var classValue = JSValue.CreateFunction(ObjectConstructor, "Object", "function Object() { [native code] }", 1);
        var @class = (JSObject)classValue;
        objectClass = @class;

        if (register)
            context[objectKey] = classValue;

        var prototype = ((IJSFunction)classValue).Prototype as JSObject;

        // Per ES2024 §20.1.2.1, Object.prototype is a NON-writable data property of the
        // Object constructor (writable: false, enumerable: false, configurable: false).
        // The CreateFunction factory installs a writable prototype that matches the
        // behaviour for user functions, but every built-in constructor's prototype is
        // non-writable; the generated factories for Array / String / Number / … all
        // explicitly install ReadonlyValue. Re-install it here for Object too (test262
        // built-ins/Object/prototype/15.2.3.1).
        @class.FastAddValue(KeyStrings.prototype, prototype, JSPropertyAttributes.ReadonlyValue);

        // ── Prototype methods ───────────────────────────────────────

        // propertyIsEnumerable
        prototype.FastAddValue(
            "propertyIsEnumerable",
            JSValue.CreateFunction(JSObject.PropertyIsEnumerable, "propertyIsEnumerable",
                "function propertyIsEnumerable() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // toString
        prototype.FastAddValue(
            "toString",
            JSValue.CreateFunction(JSObject.ToString, "toString",
                "function toString() { [native code] }", 0, false),
            JSPropertyAttributes.ConfigurableValue);

        // __proto__ (get/set property)
        prototype.FastAddProperty(
            "__proto__",
            JSValue.CreateFunction((in Arguments a) =>
                a.This is JSObject @this
                    ? @this.ObjectPrototype
                    : throw JSEngine.NewTypeError("Failed to convert this to JSObject"),
                "get __proto__"),
            JSValue.CreateFunction((in Arguments a) =>
            {
                if (a.This is JSObject @this)
                    @this.ObjectPrototype = JSValueToClrConverter.GetAsOrThrow<JSValue>(a[0], "__proto__");
                else
                    throw JSEngine.NewTypeError("Failed to convert this to JSObject");
                return JSUndefined.Value;
            },
                "set __proto__"),
            JSPropertyAttributes.ConfigurableProperty);

        // hasOwnProperty
        prototype.FastAddValue(
            "hasOwnProperty",
            JSValue.CreateFunction(JSObject.HasOwnProperty, "hasOwnProperty",
                "function hasOwnProperty() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // valueOf
        prototype.FastAddValue(
            "valueOf",
            JSValue.CreateFunction(JSObject.ValueOf, "valueOf",
                "function valueOf() { [native code] }", 0, false),
            JSPropertyAttributes.ConfigurableValue);

        // isPrototypeOf
        prototype.FastAddValue(
            "isPrototypeOf",
            JSValue.CreateFunction(JSObject.IsPrototypeOf, "isPrototypeOf",
                "function isPrototypeOf() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // ── Static methods ──────────────────────────────────────────

        // create
        @class.FastAddValue(
            "create",
            JSValue.CreateFunction(JSObject.StaticCreate, "create",
                "function create() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // assign
        @class.FastAddValue(
            "assign",
            JSValue.CreateFunction(JSObject.Assign, "assign",
                "function assign() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // defineProperties
        @class.FastAddValue(
            "defineProperties",
            JSValue.CreateFunction(JSObject.DefineProperties, "defineProperties",
                "function defineProperties() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // defineProperty
        @class.FastAddValue(
            "defineProperty",
            JSValue.CreateFunction(JSObject.DefineProperty, "defineProperty",
                "function defineProperty() { [native code] }", 3, false),
            JSPropertyAttributes.ConfigurableValue);

        // entries
        @class.FastAddValue(
            "entries",
            JSValue.CreateFunction(JSObject.GetEntries, "entries",
                "function entries() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // freeze
        @class.FastAddValue(
            "freeze",
            JSValue.CreateFunction(JSObject.Freeze, "freeze",
                "function freeze() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // fromEntries
        @class.FastAddValue(
            "fromEntries",
            JSValue.CreateFunction(JSObject.FromEntries, "fromEntries",
                "function fromEntries() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // preventExtensions
        @class.FastAddValue(
            "preventExtensions",
            JSValue.CreateFunction(JSObject.PreventExtensions, "preventExtensions",
                "function preventExtensions() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // seal
        @class.FastAddValue(
            "seal",
            JSValue.CreateFunction(JSObject.Seal, "seal",
                "function seal() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // setPrototypeOf
        @class.FastAddValue(
            "setPrototypeOf",
            JSValue.CreateFunction(JSObject.SetPrototypeOf, "setPrototypeOf",
                "function setPrototypeOf() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // groupBy (experimental): do not construct its function when disabled.
        if (context is JSContext jsContext
            && jsContext.HasExperimentalFeature(JavaScriptFeatureFlags.ObjectMapGroupBy))
        {
            @class.FastAddValue(
                "groupBy",
                JSValue.CreateFunction(JSObject.GroupBy, "groupBy",
                    "function groupBy() { [native code] }", 2, false),
                JSPropertyAttributes.ConfigurableValue);
        }

        // ── Static introspection methods ────────────────────────────

        // entries (static, overwrites previous)
        @class.FastAddValue(
            "entries",
            JSValue.CreateFunction(JSObject.StaticEntries, "entries",
                "function entries() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // is
        @class.FastAddValue(
            "is",
            JSValue.CreateFunction(JSObject.Is, "is",
                "function is() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // isExtensible
        @class.FastAddValue(
            "isExtensible",
            JSValue.CreateFunction(JSObject.IsExtensible, "isExtensible",
                "function isExtensible() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // isFrozen
        @class.FastAddValue(
            "isFrozen",
            JSValue.CreateFunction(JSObject.IsFrozen, "isFrozen",
                "function isFrozen() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // isSealed
        @class.FastAddValue(
            "isSealed",
            JSValue.CreateFunction(JSObject.IsSealed, "isSealed",
                "function isSealed() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // keys
        @class.FastAddValue(
            "keys",
            JSValue.CreateFunction(JSObject.Keys, "keys",
                "function keys() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // values
        @class.FastAddValue(
            "values",
            JSValue.CreateFunction(JSObject.Values, "values",
                "function values() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyDescriptor
        @class.FastAddValue(
            "getOwnPropertyDescriptor",
            JSValue.CreateFunction(JSObject.GetOwnPropertyDescriptor, "getOwnPropertyDescriptor",
                "function getOwnPropertyDescriptor() { [native code] }", 2, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyDescriptors
        @class.FastAddValue(
            "getOwnPropertyDescriptors",
            JSValue.CreateFunction(JSObject.GetOwnPropertyDescriptors, "getOwnPropertyDescriptors",
                "function getOwnPropertyDescriptors() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertyNames
        @class.FastAddValue(
            "getOwnPropertyNames",
            JSValue.CreateFunction(JSObject.GetOwnPropertyNames, "getOwnPropertyNames",
                "function getOwnPropertyNames() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getOwnPropertySymbols
        @class.FastAddValue(
            "getOwnPropertySymbols",
            JSValue.CreateFunction(JSObject.GetOwnPropertySymbols, "getOwnPropertySymbols",
                "function getOwnPropertySymbols() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        // getPrototypeOf
        @class.FastAddValue(
            "getPrototypeOf",
            JSValue.CreateFunction(JSObject.GetPrototypeOf, "getPrototypeOf",
                "function getPrototypeOf() { [native code] }", 1, false),
            JSPropertyAttributes.ConfigurableValue);

        return classValue;
    }
}
