using Broiler.JavaScript.ExpressionCompiler;
using Broiler.JavaScript.Storage;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Broiler.JavaScript.Runtime;


internal delegate void PropertyChangedEventHandler(JSObject sender, (uint keyString, uint index, IJSSymbol symbol) index);

[JSBaseClass("Object")]
public partial class JSObject : JSValue
{
    private IJSPrototype currentPrototype;
    protected bool HasIterator = false;
    protected bool HasAsyncIterator = false;

    /// <summary>
    /// Returns the Object prototype from the current execution context.
    /// This was formerly source-generated by JSFunctionGenerator; now uses
    /// the <see cref="GetCurrentObjectPrototype"/> delegate wired by Core.
    /// </summary>
    protected override JSValue GetCurrentPrototype() => GetCurrentObjectPrototype?.Invoke();

    /// <summary>
    /// Factory delegate for creating prototype instances.
    /// Wired by BuiltInsAssemblyInitializer at startup.
    /// </summary>
    internal static Func<JSObject, IJSPrototype> CreatePrototype;

    // ── Factory delegates for abstracting Core dependencies ──
    // These are wired by CoreAssemblyInitializer so that JSObject
    // (in Runtime) can access Core functionality without a direct reference.
    internal new static Func<string, Exception> NewTypeError;
    internal static Func<string, Exception> NewRangeError;
    internal static Func<JSObject> GetCurrentObjectPrototype;
    internal static Func<string, double> CoerceToNumber;
    internal static Func<JSValue, JSValue> CreatePrimitiveObject;

    // Error message constants (originally from JSException in Core)
    internal const string Cannot_convert_undefined_or_null_to_object = "Cannot convert undefined or null to object";
    internal const string Parameter_is_not_an_object = "Parameter is not an object";
    internal static string NotIterable(object name) => $"{name} is not iterable";
    internal static string NotEntry(object name) => $"Iterator value {name} is an entry object";

    // CLR conversion delegates (originally in CoreInternalHelpers)
    internal delegate bool TryConvertDelegate(JSValue value, Type type, out object result);
    internal static TryConvertDelegate TryGetClrEnumeratorFunc;
    internal delegate bool TryUnmarshalDelegate(JSObject obj, Type type, out object result);
    internal static TryUnmarshalDelegate TryUnmarshalObject;

    public override JSValue BasePrototypeObject
    {
        set
        {
            var prototype = value as JSObject;
            prototype?.MarkUsedAsPrototype();

            // Distinguish a brand-new object adopting its FIRST prototype (every
            // `new JSObject()`, which runs this from the constructor) from a real
            // [[SetPrototypeOf]] on a live object. Only the latter can invalidate anything:
            // nothing can hold a cached assumption about a chain that did not exist a moment
            // ago, and an object that is not yet anyone's prototype is in no other object's
            // chain — becoming one goes through MarkUsedAsPrototype, which publishes the
            // version itself. Bumping unconditionally made the prototype version advance once
            // per object allocation, which would leave any prototype-keyed cache permanently
            // invalid in a loop that allocates. See docs/performance-roadmap.md P1-2.
            var previousChain = prototypeChain;
            prototypeChain = prototype?.PrototypeObject;

            // A write that does not CHANGE the chain invalidates nothing. Every cached
            // assumption guarded by the prototype version is about which chain this object
            // has, and after a redundant write it still has the same one. Without this test a
            // re-assignment of the prototype an object already had — which class construction
            // does once per `new`, re-applying the newTarget-derived prototype the constructor
            // had already installed — retired every prototype-keyed inline-cache entry in the
            // process. That is item 2-0's defect surviving on the class path: 2-0 removed the
            // second write in JSFunction's OrdinaryCreateFromConstructor and JSClass removed
            // its own at construction, but the later re-apply still read as a mutation.
            var chainChanged = !ReferenceEquals(previousChain, prototypeChain);
            if (chainChanged && (previousChain != null || isUsedAsPrototype))
                NotifyPrototypeChainMutation();

            PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));
            currentPrototype?.Dirty();
        }
    }

    internal IJSPrototype PrototypeObject
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => currentPrototype ??= CreatePrototype(this);
    }

    internal void Dirty() => PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));

    internal ObjectStatus status = ObjectStatus.None;

    // internal long version = 0;
    internal event PropertyChangedEventHandler PropertyChanged;
    private ElementArray elements;
    private PropertySequence ownProperties;
    private SAUint32Map<JSProperty> symbols;
    private ObjectShape objectShape = ObjectShape.Empty;
    private JSValue[] shapeSlots = Array.Empty<JSValue>();
    private long? uid;

    private bool isUsedAsPrototype;
    private static long indexedPrototypeVersion;
    private static long prototypeMutationVersion;

    internal static long IndexedPrototypeVersion => Interlocked.Read(ref indexedPrototypeVersion);
    internal static long PrototypeMutationVersion => Interlocked.Read(ref prototypeMutationVersion);

    internal void MarkUsedAsPrototype()
    {
        if (isUsedAsPrototype)
            return;
        isUsedAsPrototype = true;
        Interlocked.Increment(ref indexedPrototypeVersion);
        InvalidatePrototypeAssumptions();
    }

    internal void NotifyIndexedPropertyMutation()
    {
        if (isUsedAsPrototype)
        {
            Interlocked.Increment(ref indexedPrototypeVersion);
            InvalidatePrototypeAssumptions();
        }
    }

    internal void NotifyNamedPropertyMutation()
    {
        if (isUsedAsPrototype)
            InvalidatePrototypeAssumptions();
    }

    internal static void NotifyPrototypeChainMutation()
    {
        Interlocked.Increment(ref indexedPrototypeVersion);
        InvalidatePrototypeAssumptions();
    }

    private static void InvalidatePrototypeAssumptions()
    {
        Interlocked.Increment(ref prototypeMutationVersion);
        PropertyOptimizationDiagnostics.RecordPrototypeInvalidation();
    }

    /// <summary>
    /// Whether this object's named data properties may be tracked by an
    /// <see cref="ObjectShape"/>, and so reached by an inline cache.
    /// </summary>
    /// <remarks>
    /// Virtual rather than an exact-type test so a subclass can opt in, which is what item 2-2
    /// of <c>docs/performance-roadmap.md</c> asks for. It is an opt-IN and the default is still
    /// "only an exact <see cref="JSObject"/>", because a subclass has to earn it by keeping one
    /// invariant: **while an object is in shape mode, the shape's tracked keys must be its
    /// complete set of own named properties.** Everything built on shapes relies on it —
    /// <see cref="GetPrototypeLookupShapeId"/> reads "key absent from the shape" as "no own
    /// property shadows the prototype's", and <see cref="TryCreateShapeSlot"/> reads it as
    /// "creating this key is safe".
    /// <para>
    /// The ordinary paths uphold it by construction: every addition that cannot be tracked
    /// routes through <see cref="AbandonObjectShape"/> first. A subclass that writes its own
    /// named properties straight into the property map — <c>ownProperties.Put</c> without the
    /// matching <see cref="TrackShapeDataProperty"/> — does not, and must not override this.
    /// <c>JSFunction</c> is exactly that case and is deliberately NOT opted in: it installs
    /// <c>length</c>, <c>name</c> and <c>prototype</c> with direct puts, so its shape would
    /// claim a key set that is missing three keys every function has.
    /// </para>
    /// </remarks>
    internal virtual bool SupportsShapeTracking => GetType() == typeof(JSObject);

    /// <summary>
    /// Whether a property with these attributes can occupy a shape slot.
    /// </summary>
    /// <remarks>
    /// Any plain data property qualifies, whatever its writable/enumerable/configurable
    /// flags: a slot records where the VALUE lives, and none of those flags move it. This
    /// used to demand exactly <see cref="JSPropertyAttributes.EnumerableConfigurableValue"/>,
    /// which quietly excluded every prototype object in the engine — a function's
    /// <c>prototype</c> carries a non-enumerable <c>constructor</c>, and class methods are
    /// non-enumerable too, so each one abandoned its shape as it was built and no inherited
    /// method could ever be cached. An accessor is still excluded: reading it runs a getter,
    /// not a slot load.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool IsShapeTrackableData(JSPropertyAttributes attributes)
        => (attributes & JSPropertyAttributes.Value) != 0
            && (attributes & JSPropertyAttributes.Property) == 0;

    /// <summary>
    /// Records that this object owns <paramref name="key"/> as a named property whose value no
    /// slot can hold, keeping the shape rather than abandoning it.
    /// </summary>
    /// <remarks>
    /// The shape's job is two claims, and only one of them needs the value. *Presence* — "key K
    /// is at slot N" — is what <see cref="TryReadShapeSlot"/> and <see cref="TryWriteShapeSlot"/>
    /// use. *Absence* — "the shape does not carry K, so this object does not own K" — is what
    /// <see cref="GetPrototypeLookupShapeId"/> and <see cref="TryCreateShapeSlot"/> use. A key
    /// present in the shape with a <c>null</c> slot keeps both claims true: absence reasoning
    /// sees the key and declines, and all three fast paths already reject a null slot or a
    /// descriptor whose value is not a <see cref="JSValue"/>, so a read or a write falls through
    /// to the generic path that knows how to realize it.
    /// <para>
    /// That is what lets an ordinary non-strict function be shape-tracked at all. Every one
    /// carries the Annex B <c>caller</c> and <c>arguments</c> as deferred cells from birth
    /// (P0-3), and abandoning the shape for them meant no function could keep one — which is
    /// roadmap item 2-8, and why DeltaBlue's `Strength.REQUIRED` was a 100% cache miss.
    /// </para>
    /// </remarks>
    internal void TrackShapeKeyWithoutSlotValue(in KeyString key)
    {
        if (!SupportsShapeTracking || objectShape.IsDictionary)
            return;

        if (key.Metadata.IsPrivateName)
        {
            // A private name is per-class-evaluation, so admitting one would mint a shape per
            // class instantiation rather than share a chain. Not worth a slot it cannot use.
            AbandonObjectShape();
            NotifyNamedPropertyMutation();
            return;
        }

        // A null-slot key's descriptor can only live in the trie, so it breaks the shape-only
        // invariant (item 2-9) that every shape key has a value and a data attribute set.
        // Materialize before recording one. The sole caller already writes the descriptor
        // first, which materializes anyway; this keeps the rule with the code that needs it.
        if (!namedPropertiesMaterialized)
            MaterializeNamedProperties();

        if (!objectShape.TryGetSlot(key.Key, out var slot))
        {
            objectShape = objectShape.Add(key.Key);
            slot = objectShape.SlotCount - 1;
            EnsureShapeSlotCapacity(objectShape.SlotCount);
        }

        // Cleared, not left alone: if this key previously held a fast value, the descriptor it
        // now has is the truth and the slot must stop answering for it.
        shapeSlots[slot] = null;
        shapeAttributes[slot] = JSPropertyAttributes.Empty;
        NotifyNamedPropertyMutation();
    }

    internal void TrackShapeDataProperty(in KeyString key, JSValue value, JSPropertyAttributes attributes)
    {
        if (!SupportsShapeTracking)
            return;

        if (objectShape.IsDictionary
            || value == null
            || key.Metadata.IsPrivateName
            || !IsShapeTrackableData(attributes))
        {
            AbandonObjectShape();
            NotifyNamedPropertyMutation();
            return;
        }

        if (!objectShape.TryGetSlot(key.Key, out var slot))
        {
            objectShape = objectShape.Add(key.Key);
            slot = objectShape.SlotCount - 1;
            EnsureShapeSlotCapacity(objectShape.SlotCount);
        }

        shapeSlots[slot] = value;
        shapeAttributes[slot] = attributes;
        NotifyNamedPropertyMutation();
    }

    internal void AbandonObjectShape()
    {
        if (!SupportsShapeTracking || objectShape.IsDictionary)
            return;

        // While an object is shape-only (item 2-9) the shape is the ONLY copy of its named
        // properties, so it has to be written back to the trie before it is dropped. Doing it
        // here rather than at each caller is what makes the rule hold for all of them: every
        // route into dictionary mode goes through this method.
        if (!namedPropertiesMaterialized)
            MaterializeNamedProperties();

        objectShape = ObjectShape.Dictionary;
        shapeSlots = Array.Empty<JSValue>();
        shapeAttributes = Array.Empty<JSPropertyAttributes>();
        PropertyOptimizationDiagnostics.RecordDictionaryFallback();
    }

    /// <summary>
    /// Whether a shape fast path may write this key's slot directly, bypassing this type's
    /// <c>[[Set]]</c> and <c>DefineProperty</c> overrides.
    /// </summary>
    /// <remarks>
    /// The shape fast paths write <c>ownProperties</c> and <c>shapeSlots</c> and nothing else.
    /// That is the whole point of them, and it is correct for a plain object — but a derived
    /// type may keep state <em>derived</em> from a property, synced by overriding every
    /// observable write path. <see cref="TryWriteShapeSlot"/> is not one of those paths, so for
    /// such a key the fast path would leave the object internally inconsistent.
    /// <para>
    /// Checked on the write and on the install, not just the install: shapes are interned by key
    /// set, so a <c>JSFunction</c> and a plain object that happen to carry the same keys share
    /// one shape <em>and one id</em>. An entry installed against the plain object would otherwise
    /// hit the function.
    /// </para>
    /// <para>
    /// This is not the same guard as the null slot <see cref="TrackShapeKeyWithoutSlotValue"/>
    /// installs. That one works because a deferred cell's stored value is not a
    /// <see cref="JSValue"/>, which the write paths already reject; a key like a function's
    /// <c>prototype</c> holds an ordinary JSValue and would sail through every existing check.
    /// </para>
    /// </remarks>
    internal virtual bool AllowsDirectShapeWrite(uint key) => true;

    internal bool TryGetShapeSlot(in KeyString key, out int shapeId, out int slot)
    {
        if (SupportsShapeTracking
            && !objectShape.IsDictionary
            && objectShape.TryGetSlot(key.Key, out slot))
        {
            shapeId = objectShape.Id;
            return true;
        }

        shapeId = 0;
        slot = -1;
        return false;
    }

    /// <summary>
    /// The slot for a key that is not only tracked but currently WRITABLE through it — what a
    /// store cache needs before it is worth recording an entry.
    /// </summary>
    /// <remarks>
    /// A shape tracks any data property, read-only ones included, because a slot records where
    /// the value lives and that does not depend on writability. A store entry for a read-only
    /// property would therefore be installed happily and then decline every write it was
    /// consulted for, so the descriptor is checked once here instead of on every store.
    /// </remarks>
    internal bool TryGetWritableShapeSlot(in KeyString key, out int shapeId, out int slot)
    {
        if (!TryGetShapeSlot(in key, out shapeId, out slot) || !AllowsDirectShapeWrite(key.Key))
            return false;

        // Shape-only (item 2-9): the attributes are the parallel array's, and the "is a stored
        // JSValue" test is the slot being non-null — the two facts the trie was consulted for.
        if (IsShapeOnlyStorage)
        {
            if ((uint)slot >= (uint)shapeSlots.Length || shapeSlots[slot] == null)
                return false;

            var attributes = shapeAttributes[slot];
            return (attributes & JSPropertyAttributes.Value) != 0
                && (attributes & JSPropertyAttributes.Readonly) == 0;
        }

        ref var own = ref ownProperties.GetValue(key.Key);
        return own.IsValue && !own.IsReadOnly && own.value is JSValue;
    }

    /// <summary>
    /// The receiver's shape id for a lookup that resolved on the PROTOTYPE chain, or 0 when
    /// this receiver cannot be safely keyed by shape.
    /// </summary>
    /// <remarks>
    /// Requires a shape that is neither <see cref="ObjectShape.Dictionary"/> nor
    /// <see cref="ObjectShape.Empty"/>, because both are shared by every object in that state
    /// — two unrelated dictionary-mode receivers would report the same id while disagreeing
    /// about their own properties and their prototypes. A concrete shape is not shared that
    /// way: it is reached only by adding exactly its key set, and while an object is in shape
    /// mode its tracked keys ARE its complete set of own named properties (any untrackable
    /// addition abandons the shape). So "key absent from this shape" genuinely means "no own
    /// property shadows the prototype's".
    /// </remarks>
    internal int GetPrototypeLookupShapeId(in KeyString key)
    {
        var shape = objectShape;
        if (!SupportsShapeTracking
            || shape.IsDictionary
            || ReferenceEquals(shape, ObjectShape.Empty)
            || shape.TryGetSlot(key.Key, out _))
        {
            return 0;
        }

        return shape.Id;
    }

    /// <summary>Shape id as observed by a cache guard; 0 when not shape-keyable.</summary>
    internal int CurrentShapeId => objectShape.IsDictionary ? 0 : objectShape.Id;

    /// <summary>
    /// The immediate [[Prototype]] as a plain object, read straight off the chain link.
    /// Unlike <see cref="GetPrototypeOf"/> this is non-virtual and fires no Proxy trap, so it
    /// is safe to walk from inside a cache guard or while populating one.
    /// </summary>
    internal JSObject PrototypeChainObject => prototypeChain?.Object as JSObject;

    /// <summary>
    /// Reads a slot an inline cache previously resolved on a receiver of the same shape.
    /// </summary>
    /// <remarks>
    /// The shape id alone validates the read. An <see cref="ObjectShape"/> is immutable and
    /// its key-to-slot map is fixed at construction, so two objects reporting the same shape
    /// id necessarily agree on which slot a given key occupies — re-resolving the key through
    /// the shape's dictionary, as this used to, only re-derived the slot the cache had already
    /// recorded and threw away the point of caching it. Anything that could invalidate the
    /// mapping (a delete, an accessor or non-default-attribute redefinition, a private name,
    /// or any mutable access from outside this assembly) routes through
    /// <see cref="AbandonObjectShape"/>, which swaps in the dictionary shape and so changes
    /// the id. The remaining bounds and null checks are cheap and keep a stale or
    /// partially-initialized cache entry from reading out of range.
    /// </remarks>
    /// <summary>
    /// The <see cref="TryReadShapeSlot"/> guard on its own, for a caller that reads the slot in a
    /// separate step (item 4-2b's specialized property read).
    /// </summary>
    /// <remarks>
    /// Split in two because the two halves are emitted into different arms of one conditional:
    /// the guard decides, and only the taken arm reads. Nothing runs between them — they are the
    /// test and the consequent of the same branch — so the read needs no re-validation, and the
    /// duplicated slot load is a second hit on the line the guard just touched.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool HasShapeSlotValue(int shapeId, int slot)
        => objectShape.Id == shapeId
            && (uint)slot < (uint)shapeSlots.Length
            && shapeSlots[slot] != null;

    /// <summary>Reads a slot <see cref="HasShapeSlotValue"/> has just validated.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal JSValue ReadShapeSlotUnchecked(int slot) => shapeSlots[slot];

    internal bool TryReadShapeSlot(int shapeId, int slot, out JSValue value)
    {
        if (objectShape.Id == shapeId
            && (uint)slot < (uint)shapeSlots.Length)
        {
            value = shapeSlots[slot];
            return value != null;
        }

        value = null;
        return false;
    }

    /// <summary>
    /// Overwrites a slot a store inline cache previously resolved on a receiver of the same
    /// shape. Returns false when this receiver cannot take the write, leaving the caller to
    /// run the ordinary [[Set]].
    /// </summary>
    /// <remarks>
    /// The shape id answers <em>which slot</em>, never <em>may I write to it</em>. Making a
    /// property non-writable — directly, or through <c>Object.freeze</c> — rewrites its
    /// attributes in place and deliberately keeps the shape, because a slot records where the
    /// VALUE lives and read-only does not move it. So the descriptor still has to be read, and
    /// that read is also what supplies the attributes to preserve. It is one lookup rather than
    /// the two the generic path performs, and it replaces
    /// <see cref="TrackShapeDataProperty"/>'s key-to-slot re-resolution with the cached slot.
    /// <para>
    /// Note what is deliberately absent: no extensibility or frozen test. Both only bear on
    /// whether a property may be ADDED or whether it is writable, and an existing own data
    /// property that still reports writable answers the second question by itself.
    /// </para>
    /// </remarks>
    internal bool TryWriteShapeSlot(int shapeId, int slot, in KeyString key, JSValue value)
    {
        if (value == null
            || objectShape.Id != shapeId
            || (uint)slot >= (uint)shapeSlots.Length
            || !AllowsDirectShapeWrite(key.Key))
        {
            return false;
        }

        // Shape-only (item 2-9): no descriptor exists to read or rewrite. The attributes stay
        // exactly as they were — this overwrites a value, which is the one thing a store may
        // do without touching them — so only the slot moves.
        if (IsShapeOnlyStorage)
        {
            if (shapeSlots[slot] == null)
                return false;

            var attributes = shapeAttributes[slot];
            if ((attributes & JSPropertyAttributes.Value) == 0
                || (attributes & JSPropertyAttributes.Readonly) != 0)
            {
                return false;
            }

            shapeSlots[slot] = value;
            NotifyNamedPropertyMutation();
            PropertyChanged?.Invoke(this, (key.Key, uint.MaxValue, null));
            return true;
        }

        ref var own = ref ownProperties.GetValue(key.Key);
        if (!own.IsValue || own.IsReadOnly || own.value is not JSValue)
            return false;

        // Written through the ref the lookup already produced; re-entering the map to Put
        // would walk it a second time for a node that is known to exist.
        own = new JSProperty(key, value, own.Attributes);
        shapeSlots[slot] = value;
        NotifyNamedPropertyMutation();
        PropertyChanged?.Invoke(this, (key.Key, uint.MaxValue, null));
        return true;
    }

    /// <summary>
    /// The shape a store cache may record a transition out of, or <c>null</c> when this
    /// receiver cannot be keyed by one.
    /// </summary>
    /// <remarks>
    /// A concrete shape is by itself proof that a key it does not carry is absent from the
    /// object: while an object is in shape mode its tracked keys ARE its complete set of own
    /// named properties, because every addition that cannot be tracked — a private name, an
    /// accessor, a non-default attribute set, a deferred cell — calls
    /// <see cref="AbandonObjectShape"/> first. Dictionary mode carries no such guarantee and is
    /// excluded. <see cref="ObjectShape.Empty"/> is deliberately NOT excluded even though every
    /// fresh object shares it: it is exactly the state a constructor's first field assignment
    /// starts from, and sharing is harmless because a transition is determined by the shape and
    /// the key alone — unlike <see cref="GetPrototypeLookupShapeId"/>, which must reject it
    /// because there the shared id would have to stand in for the receiver's identity.
    /// </remarks>
    internal ObjectShape TransitionShape
        => SupportsShapeTracking && !objectShape.IsDictionary ? objectShape : null;

    /// <summary>
    /// Creates the key as a fresh own data property, in a slot and a successor shape a store
    /// inline cache has already resolved. Returns false when this receiver cannot take the
    /// creation, leaving the caller to run the ordinary [[Set]].
    /// </summary>
    /// <remarks>
    /// The write twin of <see cref="TryWriteShapeSlot"/> for the case that one cannot serve:
    /// a store that does not overwrite an existing slot but adds one. That is
    /// CreateDataProperty, the last step of OrdinarySetWithOwnDescriptor, so three things must
    /// hold and only two of them are checked here — the shape must be exactly the one the
    /// transition was recorded from, the object must still be extensible, and nothing on the
    /// prototype chain may supply the key. The third belongs to the caller, which is where the
    /// chain was walked and where the guards that detect it changing live.
    /// <para>
    /// Extensibility is checked, unlike in <see cref="TryWriteShapeSlot"/>, precisely because
    /// this call ADDS a property: <c>Object.preventExtensions</c>, <c>seal</c> and
    /// <c>freeze</c> all set <see cref="ObjectStatus.NonExtensible"/>, so one test covers all
    /// three. A rejected creation is not reported here either — returning false runs the
    /// generic path, which throws or returns false exactly as it did before.
    /// </para>
    /// </remarks>
    internal bool TryCreateShapeSlot(
        ObjectShape from,
        ObjectShape to,
        int slot,
        in KeyString key,
        JSValue value)
    {
        if (value == null
            || !SupportsShapeTracking
            || !ReferenceEquals(objectShape, from)
            || (status & ObjectStatus.NonExtensible) != 0
            || !AllowsDirectShapeWrite(key.Key))
        {
            return false;
        }

        EnsureShapeSlotCapacity(Math.Max(to.SlotCount, slot + 1));

        // The same three steps DefineReceiverDataProperty performs for an ordinary target,
        // with the shape advanced to the recorded successor instead of being re-derived:
        // TrackShapeDataProperty would look the key up in the current shape, miss, and then
        // look it up again in that shape's transition table to find the very shape and slot
        // this entry already holds.
        //
        // Shape-only (item 2-9) drops the first of those steps as well: a creation that stays
        // out of the trie allocates no radix-trie nodes at all, which is the whole prize.
        if (!IsShapeOnlyStorage)
            ownProperties.Put(key, value, JSPropertyAttributes.EnumerableConfigurableValue);

        objectShape = to;
        shapeSlots[slot] = value;
        shapeAttributes[slot] = JSPropertyAttributes.EnumerableConfigurableValue;
        NotifyNamedPropertyMutation();
        PropertyChanged?.Invoke(this, (key.Key, uint.MaxValue, null));
        return true;
    }

    internal bool HasIndexedPropertiesOnPrototypeChain()
    {
        for (var current = prototypeChain?.Object as JSObject; current != null; current = current.prototypeChain?.Object as JSObject)
        {
            if (current.elements.Count != 0)
                return true;
        }
        return false;
    }

    private static long NextID = 0;
    internal long UniqueID => uid ??= Interlocked.Increment(ref NextID);

    public override bool BooleanValue => true;

    public override bool IsObject => true;


    public JSObject() : base(null) { }

    internal protected JSObject(JSObject prototype = null) : base(prototype) { }

    public virtual IEnumerable<(string Key, JSValue value)> Entries
    {
        get
        {
            var es = GetElementEnumerator();

            while (es.MoveNext(out var hasValue, out var value, out var index))
            {
                if (hasValue)
                    yield return (index.ToString(), value);
            }

            var ownProperties = GetOwnProperties();
            var en = new PropertyValueEnumerator(this, false);

            while (en.MoveNext(out var value, out var key))
                yield return (KeyStrings.GetNameString(key.Key).Value, value);
        }
    }

    public JSObject(IEnumerable<JSProperty> entries) : this(GetCurrentObjectPrototype())
    {
        AbandonObjectShape();
        ref var own = ref OwnProperties();
        foreach (var p in entries)
            own.Put(p.key) = p;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithProperties() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithElements() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithPropertiesAndElements() => new JSObject { };

    private bool toStringCalled = false;

    public override double DoubleValue
    {
        get
        {
            try
            {
                return ToPrimitive(preferString: false).DoubleValue;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw JSException.From(ex);
            }
        }
    }

    public override string StringValue
    {
        get
        {
            try
            {
                return ToPrimitive(preferString: true).StringValue;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw;
            }
        }
    }

    public override int Length
    {
        get
        {
            try
            {
                // Shape-only (item 2-9): the trie is empty and would report no `length` at
                // all, so the answer comes from the shape. Deliberately not a materialize —
                // this runs on ordinary objects used as array-likes, and materializing here
                // would give the trie back to exactly the objects the item is about.
                if (IsShapeOnlyStorage)
                {
                    if (!TryGetShapeOnlyProperty(KeyStrings.length.Key, out var lp))
                        return -1;

                    return (int)(((uint)GetValue(lp).DoubleValue) >> 0);
                }

                ref var ownp = ref ownProperties;
                if (ownp.IsEmpty)
                    return -1;

                ref var l = ref ownp.GetValue(KeyStrings.length.Key);
                if (!l.IsEmpty)
                {
                    var n = GetValue(l);
                    var nvalue = ((uint)n.DoubleValue) >> 0;
                    return (int)nvalue;
                }

                return -1;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw JSException.From(ex);
            }
        }
        set
        {
            if (IsSealedOrFrozenOrNonExtensible())
                throw NewTypeError($"Cannot modify property length of {this}");

            ref var ownp = ref GetOwnProperties();
            ownp.Put(KeyStrings.length, CreateNumber(value));
            PropertyChanged?.Invoke(this, (KeyStrings.length.Key, uint.MaxValue, null));
        }
    }

    private JSValue ToPrimitive(bool preferString)
    {
        var toPrimitiveSymbol = GetGlobalSymbolFactory?.Invoke("toPrimitive");
        if (toPrimitiveSymbol != null)
        {
            var exoticToPrimitive = this[toPrimitiveSymbol];
            if (!exoticToPrimitive.IsUndefined && !exoticToPrimitive.IsNull)
            {
                if (!exoticToPrimitive.IsFunction)
                    throw NewTypeError("@@toPrimitive is not a function");

                var hint = CreateString(preferString ? "string" : "number");
                var primitive = exoticToPrimitive.InvokeFunction(new Arguments(this, hint));
                if (!primitive.IsObject)
                    return primitive;

                throw NewTypeError("Cannot convert object to primitive value");
            }
        }

        return OrdinaryToPrimitive(preferString);
    }

    private JSValue ToPrimitiveDefault()
    {
        var toPrimitiveSymbol = GetGlobalSymbolFactory?.Invoke("toPrimitive");
        if (toPrimitiveSymbol != null)
        {
            var exoticToPrimitive = this[toPrimitiveSymbol];
            if (!exoticToPrimitive.IsUndefined && !exoticToPrimitive.IsNull)
            {
                if (!exoticToPrimitive.IsFunction)
                    throw NewTypeError("@@toPrimitive is not a function");

                var primitive = exoticToPrimitive.InvokeFunction(new Arguments(this, CreateString("default")));
                if (!primitive.IsObject)
                    return primitive;

                throw NewTypeError("Cannot convert object to primitive value");
            }
        }

        // The default hint behaves as the number hint for OrdinaryToPrimitive. Call it
        // directly rather than delegating to ToPrimitive(false), which would re-read
        // @@toPrimitive — an observable second [[Get]] of the symbol property.
        return OrdinaryToPrimitive(preferString: false);
    }

    // OrdinaryToPrimitive(O, hint): try valueOf/toString (or toString/valueOf for the
    // string hint) without consulting @@toPrimitive (the caller already did).
    private JSValue OrdinaryToPrimitive(bool preferString)
    {
        var firstMethod = preferString ? KeyStrings.toString : KeyStrings.valueOf;
        var secondMethod = preferString ? KeyStrings.valueOf : KeyStrings.toString;

        var first = TryCallPrimitiveMethod(firstMethod);
        if (first != null)
            return first;

        var second = TryCallPrimitiveMethod(secondMethod);
        if (second != null)
            return second;

        throw NewTypeError("Cannot convert object to primitive value");
    }

    internal JSValue ToDefaultPrimitive() => ToPrimitiveDefault();

    // ToPrimitive with the "string" hint (calls @@toPrimitive / toString-then-valueOf). The result
    // is a primitive that the caller may still need to type-check (e.g. spec ToPrimitiveAndRequireString).
    internal JSValue ToStringPrimitive() => ToPrimitive(preferString: true);

    // ToPrimitive with the "number" hint (valueOf-then-toString). Used by the
    // relational operators, whose hint is Number — distinct from the "default" hint
    // used by `==`, which differs for objects such as Date (default behaves as string).
    internal JSValue ToNumberPrimitive() => ToPrimitive(preferString: false);

    private JSValue TryCallPrimitiveMethod(in KeyString key)
    {
        var method = this[key];
        if (!method.IsFunction)
            return null;

        var primitive = method.InvokeFunction(new Arguments(this));
        return primitive.IsObject ? null : primitive;
    }
}
