using Broiler.JavaScript.ExpressionCompiler;
using Broiler.JavaScript.Storage;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Broiler.JavaScript.Runtime;


internal delegate void PropertyChangedEventHandler(JSObject sender, (uint keyString, uint index, IJSSymbol symbol) index);

[JSBaseClass("Object")]
public partial class JSObject : JSValue
{
    private IJSPrototype currentPrototype;
    protected bool HasIterator = false;
    protected bool HasAsyncIterator = false;

    /// <summary>
    /// Returns the Object prototype from the current execution context.
    /// This was formerly source-generated by JSFunctionGenerator; now uses
    /// the <see cref="GetCurrentObjectPrototype"/> delegate wired by Core.
    /// </summary>
    protected override JSValue GetCurrentPrototype() => GetCurrentObjectPrototype?.Invoke();

    /// <summary>
    /// Factory delegate for creating prototype instances.
    /// Wired by BuiltInsAssemblyInitializer at startup.
    /// </summary>
    internal static Func<JSObject, IJSPrototype> CreatePrototype;

    // ── Factory delegates for abstracting Core dependencies ──
    // These are wired by CoreAssemblyInitializer so that JSObject
    // (in Runtime) can access Core functionality without a direct reference.
    internal new static Func<string, Exception> NewTypeError;
    internal static Func<string, Exception> NewRangeError;
    internal static Func<JSObject> GetCurrentObjectPrototype;
    internal static Func<string, double> CoerceToNumber;
    internal static Func<JSValue, JSValue> CreatePrimitiveObject;

    // Error message constants (originally from JSException in Core)
    internal const string Cannot_convert_undefined_or_null_to_object = "Cannot convert undefined or null to object";
    internal const string Parameter_is_not_an_object = "Parameter is not an object";
    internal static string NotIterable(object name) => $"{name} is not iterable";
    internal static string NotEntry(object name) => $"Iterator value {name} is an entry object";

    // CLR conversion delegates (originally in CoreInternalHelpers)
    internal delegate bool TryConvertDelegate(JSValue value, Type type, out object result);
    internal static TryConvertDelegate TryGetClrEnumeratorFunc;
    internal delegate bool TryUnmarshalDelegate(JSObject obj, Type type, out object result);
    internal static TryUnmarshalDelegate TryUnmarshalObject;

    public override JSValue BasePrototypeObject
    {
        set
        {
            var prototype = value as JSObject;
            prototype?.MarkUsedAsPrototype();
            prototypeChain = prototype?.PrototypeObject;
            NotifyPrototypeChainMutation();
            PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));
            currentPrototype?.Dirty();
        }
    }

    internal IJSPrototype PrototypeObject
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => currentPrototype ??= CreatePrototype(this);
    }

    internal void Dirty() => PropertyChanged?.Invoke(this, (uint.MaxValue, uint.MaxValue, null));

    internal ObjectStatus status = ObjectStatus.None;

    // internal long version = 0;
    internal event PropertyChangedEventHandler PropertyChanged;
    private ElementArray elements;
    private PropertySequence ownProperties;
    private SAUint32Map<JSProperty> symbols;
    private ObjectShape objectShape = ObjectShape.Empty;
    private JSValue[] shapeSlots = Array.Empty<JSValue>();
    private long? uid;

    private bool isUsedAsPrototype;
    private static long indexedPrototypeVersion;
    private static long prototypeMutationVersion;

    internal static long IndexedPrototypeVersion => Interlocked.Read(ref indexedPrototypeVersion);
    internal static long PrototypeMutationVersion => Interlocked.Read(ref prototypeMutationVersion);

    internal void MarkUsedAsPrototype()
    {
        if (isUsedAsPrototype)
            return;
        isUsedAsPrototype = true;
        Interlocked.Increment(ref indexedPrototypeVersion);
        InvalidatePrototypeAssumptions();
    }

    internal void NotifyIndexedPropertyMutation()
    {
        if (isUsedAsPrototype)
        {
            Interlocked.Increment(ref indexedPrototypeVersion);
            InvalidatePrototypeAssumptions();
        }
    }

    internal void NotifyNamedPropertyMutation()
    {
        if (isUsedAsPrototype)
            InvalidatePrototypeAssumptions();
    }

    internal static void NotifyPrototypeChainMutation()
    {
        Interlocked.Increment(ref indexedPrototypeVersion);
        InvalidatePrototypeAssumptions();
    }

    private static void InvalidatePrototypeAssumptions()
    {
        Interlocked.Increment(ref prototypeMutationVersion);
        PropertyOptimizationDiagnostics.RecordPrototypeInvalidation();
    }

    internal void TrackShapeDataProperty(in KeyString key, JSValue value, JSPropertyAttributes attributes)
    {
        if (GetType() != typeof(JSObject))
            return;

        if (objectShape.IsDictionary
            || value == null
            || key.Metadata.IsPrivateName
            || attributes != JSPropertyAttributes.EnumerableConfigurableValue)
        {
            AbandonObjectShape();
            NotifyNamedPropertyMutation();
            return;
        }

        if (!objectShape.TryGetSlot(key.Key, out var slot))
        {
            objectShape = objectShape.Add(key.Key);
            slot = objectShape.SlotCount - 1;
            if (shapeSlots.Length <= slot)
            {
                var replacement = new JSValue[Math.Max(4, Math.Max(objectShape.SlotCount, shapeSlots.Length * 2))];
                Array.Copy(shapeSlots, replacement, shapeSlots.Length);
                shapeSlots = replacement;
            }
        }

        shapeSlots[slot] = value;
        NotifyNamedPropertyMutation();
    }

    internal void AbandonObjectShape()
    {
        if (GetType() != typeof(JSObject) || objectShape.IsDictionary)
            return;
        objectShape = ObjectShape.Dictionary;
        shapeSlots = Array.Empty<JSValue>();
        PropertyOptimizationDiagnostics.RecordDictionaryFallback();
    }

    internal bool TryGetShapeSlot(in KeyString key, out int shapeId, out int slot)
    {
        if (GetType() == typeof(JSObject)
            && !objectShape.IsDictionary
            && objectShape.TryGetSlot(key.Key, out slot))
        {
            shapeId = objectShape.Id;
            return true;
        }

        shapeId = 0;
        slot = -1;
        return false;
    }

    internal bool TryReadShapeSlot(int shapeId, int slot, uint key, out JSValue value)
    {
        if (GetType() == typeof(JSObject)
            && objectShape.Id == shapeId
            && !objectShape.IsDictionary
            && objectShape.TryGetSlot(key, out var actualSlot)
            && actualSlot == slot
            && (uint)slot < (uint)shapeSlots.Length
            && shapeSlots[slot] != null)
        {
            value = shapeSlots[slot];
            return true;
        }

        value = null;
        return false;
    }

    internal bool HasIndexedPropertiesOnPrototypeChain()
    {
        for (var current = prototypeChain?.Object as JSObject; current != null; current = current.prototypeChain?.Object as JSObject)
        {
            if (current.elements.Count != 0)
                return true;
        }
        return false;
    }

    private static long NextID = 0;
    internal long UniqueID => uid ??= Interlocked.Increment(ref NextID);

    public override bool BooleanValue => true;

    public override bool IsObject => true;


    public JSObject() : base(null) { }

    internal protected JSObject(JSObject prototype = null) : base(prototype) { }

    public virtual IEnumerable<(string Key, JSValue value)> Entries
    {
        get
        {
            var es = GetElementEnumerator();

            while (es.MoveNext(out var hasValue, out var value, out var index))
            {
                if (hasValue)
                    yield return (index.ToString(), value);
            }

            var ownProperties = GetOwnProperties();
            var en = new PropertyValueEnumerator(this, false);

            while (en.MoveNext(out var value, out var key))
                yield return (KeyStrings.GetNameString(key.Key).Value, value);
        }
    }

    public JSObject(IEnumerable<JSProperty> entries) : this(GetCurrentObjectPrototype())
    {
        AbandonObjectShape();
        foreach (var p in entries)
            ownProperties.Put(p.key) = p;
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithProperties() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithElements() => new() { };

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static JSObject NewWithPropertiesAndElements() => new JSObject { };

    private bool toStringCalled = false;

    public override double DoubleValue
    {
        get
        {
            try
            {
                return ToPrimitive(preferString: false).DoubleValue;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw JSException.From(ex);
            }
        }
    }

    public override string StringValue
    {
        get
        {
            try
            {
                return ToPrimitive(preferString: true).StringValue;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw;
            }
        }
    }

    public override int Length
    {
        get
        {
            try
            {
                ref var ownp = ref ownProperties;
                if (ownp.IsEmpty)
                    return -1;

                ref var l = ref ownp.GetValue(KeyStrings.length.Key);
                if (!l.IsEmpty)
                {
                    var n = GetValue(l);
                    var nvalue = ((uint)n.DoubleValue) >> 0;
                    return (int)nvalue;
                }

                return -1;
            }
            catch (JSException)
            {
                throw;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
                throw JSException.From(ex);
            }
        }
        set
        {
            if (IsSealedOrFrozenOrNonExtensible())
                throw NewTypeError($"Cannot modify property length of {this}");

            ref var ownp = ref GetOwnProperties();
            ownp.Put(KeyStrings.length, CreateNumber(value));
            PropertyChanged?.Invoke(this, (KeyStrings.length.Key, uint.MaxValue, null));
        }
    }

    private JSValue ToPrimitive(bool preferString)
    {
        var toPrimitiveSymbol = GetGlobalSymbolFactory?.Invoke("toPrimitive");
        if (toPrimitiveSymbol != null)
        {
            var exoticToPrimitive = this[toPrimitiveSymbol];
            if (!exoticToPrimitive.IsUndefined && !exoticToPrimitive.IsNull)
            {
                if (!exoticToPrimitive.IsFunction)
                    throw NewTypeError("@@toPrimitive is not a function");

                var hint = CreateString(preferString ? "string" : "number");
                var primitive = exoticToPrimitive.InvokeFunction(new Arguments(this, hint));
                if (!primitive.IsObject)
                    return primitive;

                throw NewTypeError("Cannot convert object to primitive value");
            }
        }

        return OrdinaryToPrimitive(preferString);
    }

    private JSValue ToPrimitiveDefault()
    {
        var toPrimitiveSymbol = GetGlobalSymbolFactory?.Invoke("toPrimitive");
        if (toPrimitiveSymbol != null)
        {
            var exoticToPrimitive = this[toPrimitiveSymbol];
            if (!exoticToPrimitive.IsUndefined && !exoticToPrimitive.IsNull)
            {
                if (!exoticToPrimitive.IsFunction)
                    throw NewTypeError("@@toPrimitive is not a function");

                var primitive = exoticToPrimitive.InvokeFunction(new Arguments(this, CreateString("default")));
                if (!primitive.IsObject)
                    return primitive;

                throw NewTypeError("Cannot convert object to primitive value");
            }
        }

        // The default hint behaves as the number hint for OrdinaryToPrimitive. Call it
        // directly rather than delegating to ToPrimitive(false), which would re-read
        // @@toPrimitive — an observable second [[Get]] of the symbol property.
        return OrdinaryToPrimitive(preferString: false);
    }

    // OrdinaryToPrimitive(O, hint): try valueOf/toString (or toString/valueOf for the
    // string hint) without consulting @@toPrimitive (the caller already did).
    private JSValue OrdinaryToPrimitive(bool preferString)
    {
        var firstMethod = preferString ? KeyStrings.toString : KeyStrings.valueOf;
        var secondMethod = preferString ? KeyStrings.valueOf : KeyStrings.toString;

        var first = TryCallPrimitiveMethod(firstMethod);
        if (first != null)
            return first;

        var second = TryCallPrimitiveMethod(secondMethod);
        if (second != null)
            return second;

        throw NewTypeError("Cannot convert object to primitive value");
    }

    internal JSValue ToDefaultPrimitive() => ToPrimitiveDefault();

    // ToPrimitive with the "string" hint (calls @@toPrimitive / toString-then-valueOf). The result
    // is a primitive that the caller may still need to type-check (e.g. spec ToPrimitiveAndRequireString).
    internal JSValue ToStringPrimitive() => ToPrimitive(preferString: true);

    // ToPrimitive with the "number" hint (valueOf-then-toString). Used by the
    // relational operators, whose hint is Number — distinct from the "default" hint
    // used by `==`, which differs for objects such as Date (default behaves as string).
    internal JSValue ToNumberPrimitive() => ToPrimitive(preferString: false);

    private JSValue TryCallPrimitiveMethod(in KeyString key)
    {
        var method = this[key];
        if (!method.IsFunction)
            return null;

        var primitive = method.InvokeFunction(new Arguments(this));
        return primitive.IsObject ? null : primitive;
    }
}
