// <auto-generated />
using Broiler.JavaScript.Portable;

namespace Broiler.JavaScript.NativeAotSample;

internal static class FibonacciProgram
{
    internal static readonly PortableProgram Value = new(
        "fibonacci",
        1,
        4,
        2,
        new PortableInstruction[]
        {
            new(PortableOpCode.PushConstant),
            new(PortableOpCode.StoreLocal),
            new(PortableOpCode.PushConstant, 0, 1),
            new(PortableOpCode.StoreLocal, 1),
            new(PortableOpCode.PushConstant),
            new(PortableOpCode.StoreLocal, 2),
            new(PortableOpCode.LoadLocal, 2),
            new(PortableOpCode.LoadArgument),
            new(PortableOpCode.LessThan),
            new(PortableOpCode.JumpIfFalse, 29),
            new(PortableOpCode.LoadLocal),
            new(PortableOpCode.LoadLocal, 1),
            new(PortableOpCode.Add),
            new(PortableOpCode.StoreLocal, 3),
            new(PortableOpCode.LoadLocal, 1),
            new(PortableOpCode.Duplicate),
            new(PortableOpCode.StoreLocal),
            new(PortableOpCode.Pop),
            new(PortableOpCode.LoadLocal, 3),
            new(PortableOpCode.Duplicate),
            new(PortableOpCode.StoreLocal, 1),
            new(PortableOpCode.Pop),
            new(PortableOpCode.LoadLocal, 2),
            new(PortableOpCode.PushConstant, 0, 1),
            new(PortableOpCode.Add),
            new(PortableOpCode.Duplicate),
            new(PortableOpCode.StoreLocal, 2),
            new(PortableOpCode.Pop),
            new(PortableOpCode.Jump, 6),
            new(PortableOpCode.LoadLocal),
            new(PortableOpCode.Return),
        });
}
